ChromeDevTools/awesome-chrome-devtools

- readme.md
Adds the [Zero Dark Matrix](https://chrome.google.com/webstore/detail/devtools-theme-zero-dark/bomhdjeadceaggdgfoefmpeafkjhegbo) extension to the UX category. This is a popular dark theme for DevTools.
> Add Zero Dark Matrix to extensions

- readme.md
This PR adds [Augury](https://augury.angular.io/) in the extension section, for profiling and debugging angular 2 applications.
> add augury for angular 2 apps

- readme.md
devtoolsremote.com wasn't renewed ( https://twitter.com/auchenberg/status/846214957783932928 ).
> DevTools Remote URL update

- readme.md
This PR adds [cdp](https://github.com/mafredri/cdp), a library for the protocol written in Go.
PS. I wasn't sure if I should order it or not, but since the list was unordered, I decided to append, hope that's OK.
> Add cdp (Golang)

- readme.md
In #49 I noticed the repo didn't pass linting:
```
❯ awesome-lint
13:1-13:22  error    Rules should use `---`      rule-style
66:1-66:20  error    Rules should use `---`      rule-style
93:1-93:18  error    Rules should use `---`      rule-style
✖ 3 errors
```
This PR fixes all offending entries.
> Fix rule-style by awesome-lint

- readme.md
from https://developer.chrome.com/devtools/docs/debugging-clients
Everything good and worthwhile I imported. 
Fixed a few links while I was at it.
> Import the "Showcase Chrome Debugging Protocol Clients" contents

- readme.md
Added reference to my tool  PyChromeDevTools; it is a python module that allows one to interact using Chrome DevTools Protocol within a Python script. Now more than 14 days passed from creation.
> Added PyChromeDevTools

- readme.md
Adds link to the `chromedp` package, which provides high level driving actions (akin to Selenium) for Go.
> Adding Go chromedp package to list

- readme.md
Added https://github.com/BaristaLabs/chrome-dev-tools to the list of driver libraries.
The description is a bit longer to indicate that BaristaLabs/chrome-dev-tools is in effect a protocol wrapper factory that uses handlebars templates to customize the output. It includes a pre-built template that targets .Net Core, but templates could be created that targets other languages or differing development approaches.
> Add BaristaLabs/chrome-dev-tools to the list

- readme.md
I've been working on this for the past month and have done my first public release. This library will help Python 3 developers fully leverage the devtools protocol by managing concurrent requests and event callbacks.
> Add chromewhip to protocol driver libraries

- readme.md
ref #61  
remove as it isn't a wrapper for the protocol, but rather has a higher level API thats just too simple.
> remove chromote python lib

- readme.md
A Python Package for the Google Chrome Dev Protocol
why I make another Python packages for Google Chrome Dev Protocol
* `chromote` can not use Chrome Dev Protocol directly for now
* `PyChromeDevTools` can not control multiple tabs for now
> Add pychrome

- readme.md
I build a Node.JS implementation of the Chrome Backend to run DevTools in arbitrary web environments. In my specific case I implemented a debugging platform for HbbTV apps on Smart TVs. It is a similar approach to the [Weinre](https://people.apache.org/~pmuellr/weinre/docs/latest/) project but I wanted to stay closer to the protocol. There is a WebDriver domain in the instrumentation script which can be used to run automated tests on instrumented targets. I haven't published the driver yet but will do soon. Here some examples:
- Debugging HbbTV apps on a Smart TV using Chrome DevTools
https://twitter.com/bromann/status/839943193160527872
- Running WebDriver tests using that driver on a Selenium Grid
https://twitter.com/bromann/status/890199053467885578
Hope it can be an addition to this …
> Add DevTools Backend

- readme.md
> Add link to Rust crate

- readme.md
I'm adding to projects that I've created that offer Chrome DevTools bindings for Python.
> Add PyCDP and Trio CDP

- readme.md
Taiko is a node js library to automate chrome/chromium using the DevTools protocol. 
More info at https://github.com/getgauge/taiko https://taiko.gauge.org
> Add reference to Taiko

- readme.md
It allows debugging JS running in J2V8 (V8 on Android) using Chrome DevTools.
This link could be helpful for current users of [J2V8](https://github.com/eclipsesource/J2V8) since no build-in debugger is present in the J2V8 itself.
> Add link to j2v8-debugger

- readme.md
[TracerBench](https://github.com/TracerBench/tracerbench) is a performance benchmarking tool built on the Chrome DevTools Protocol. It seems appropriate to add it to this great list!
> Adds link and description for TracerBench

- readme.md
I don't think you'll merge this PR because it looks like it's just promoting a commercial product.
I made a 'remote browser isolation' platform and share this free demo of it here. 
I heavily rely on Chrome devtools for this task so want to give back to the community by showing what's possible.
As I'm unwilling to release the source (because the full product is money-making) I'm quite sure you'll be unable to include it here.
> Added link in developing with dev tools

- readme.md
Hey @Garbee 
just a minor fix: removing a dead link to an extension which has been taken down.
Cheers!
> Removing dead extension

- readme.md
Hey @Garbee 
I feel [PuPHPeteer](https://github.com/rialto-php/puphpeteer), a PHP-bridge for Puppeteer would make a good addition. What do you think?
Cheers,
Peter
> Adding PuPHPeteer

- .github/workflows/blank.yml
The repository age is computed based on the oldest fetched commit.
The default depth 1 forces awesome-lint to use the age of the latest commit as the age of the repo (which is obviously invalid).
See:
https://github.com/sindresorhus/awesome-lint/issues/105
And the doc specifically mentions `fetch-depth: 0` here:
https://github.com/sindresorhus/awesome-lint#github-actions
> Fix awesome-lint tests

- readme.md
This PR adds [cuic](https://github.com/milankinen/cuic) which is a high-level ui test automation library for Clojure. It uses DevTools Protocol to control the browser.
> Add cuic library

- readme.md
[puppeteer-ide-extension](https://github.com/gajananpp/puppeteer-ide-extension) is a standalone chrome extension to write and execute puppeteer scripts from browser's developer tools. It executes the script on inspected tab.
> Add Puppeteer IDE extension

- readme.md
I'm not sure why, but https://github.com/muzuiget/mare doesn't exist(or private?) now.
> Remove a link to mare as it doesn't exist now

- readme.md
This PR adds [ruby/debug](https://github.com/ruby/debug). It is used Chrome DevTools Frontend.
BTW, when I implemented this feature, this lists were really helpful. Thank you!
> Add ruby/debug library

- readme.md
This is the right upstream repo
> Change puppeteer-sharp link to the org repo

- readme.md
Apparently chromelens.xyz URL is not related anymore, so I've updated the link to be the extension's page.
> Update broken link for Chromelens

- readme.md
k6-browser adds support for browser automation and end-to-end web testing via the Chrome Devtools Protocol (CDP). It uses CDP to drive browsers for testing websites.
More information about the project:
* https://grafana.com/docs/k6/latest/javascript-api/k6-browser/
* https://grafana.com/docs/k6/latest/using-k6-browser/
* https://grafana.com/docs/k6/latest/using-k6-browser/running-browser-tests/
* https://grafana.com/docs/k6/latest/using-k6-browser/metrics/
* https://grafana.com/blog/2023/01/08/how-to-add-browser-level-apis-for-web-performance-metrics/
> Add k6-browser link

- readme.md
Hi! Adding alternative .NET Chrome DevTools Protocol client library + schema code generation tools.
> Add `dotnet-chrome-protocol` library

- readme.md
Removed the extension link that's no longer availble in the chrome web store
- [Angular Batarang](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk) 
- [Augury](https://augury.angular.io/)
Added new chrome extension for Angular 
- [Angular DevTools](https://chromewebstore.google.com/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh) - https://angular.dev/tools/devtools
> Update the Angular DevTools
